<?php

declare(strict_types=1);

namespace App\Tests\Unit\Entity;

use App\Entity\Category;
use App\Entity\Movie;
use Codeception\Test\Unit;

class MovieTest extends Unit
{
    private Movie $movie;

    protected function _before(): void
    {
        $this->movie = new Movie();
    }

    public function testMovieInstantiationWithDefaults()
    {
        $this->assertNull($this->movie->getId());
        $this->assertNull($this->movie->getName());
        $this->assertNull($this->movie->getYear());
        $this->assertNull($this->movie->getCategory());
    }

    public function testSetAndGetName()
    {
        $this->movie->setName('Inception');
        $this->assertSame('Inception', $this->movie->getName());
    }

    public function testSetAndGetYear()
    {
        $this->movie->setYear(2010);
        $this->assertSame(2010, $this->movie->getYear());
    }

    public function testMovieIdIsAutoGenerated()
    {
        // Doctrine auto-generates ID
        $this->assertNull($this->movie->getId());
    }

    public function testSetAndGetCategory()
    {
        $category = new Category();
        $category->setName('Sci-Fi');

        $this->movie->setCategory($category);
        $this->assertSame($category, $this->movie->getCategory());
        $this->assertSame('Sci-Fi', $this->movie->getCategory()->getName());
    }

    public function testSetCategoryToNull()
    {
        $category = new Category();
        $this->movie->setCategory($category);
        $this->movie->setCategory(null);

        $this->assertNull($this->movie->getCategory());
    }

    public function testMovieFluentInterface()
    {
        $result = $this->movie
            ->setName('The Matrix')
            ->setYear(1999);

        $this->assertSame($this->movie, $result);
        $this->assertSame('The Matrix', $this->movie->getName());
        $this->assertSame(1999, $this->movie->getYear());
    }
}
